name: 'Gödel Code Review'
description: 'AI-powered code review with AWS Bedrock + 52-agent OpusSwarm. Exports to AWS Security Hub. Cryptographic signatures, Merkle validation, OPA policies. AWS Partner Verified (S-0084812).'
author: 'EpochCore Quantum - AWS Partner'
branding:
  icon: 'git-pull-request'
  color: 'purple'

inputs:
  mode:
    description: 'Verification mode: quick, standard, or deep'
    required: false
    default: 'standard'
  policy-path:
    description: 'Path to OPA policy files'
    required: false
    default: '.epochcore/policies'
  signature-verify:
    description: 'Enable cryptographic signature verification'
    required: false
    default: 'true'
  merkle-validate:
    description: 'Enable Merkle tree validation for file integrity'
    required: false
    default: 'true'
  fail-on-warning:
    description: 'Fail the action on warnings (not just errors)'
    required: false
    default: 'false'
  license-key:
    description: 'EpochCore license key for Pro/Enterprise features'
    required: false
    default: ''
  worker-endpoint:
    description: 'Custom EpochCore worker endpoint'
    required: false
    default: 'https://epochcore-unified-worker.epochcoreras.workers.dev'
  swarm-review:
    description: 'Enable 52-agent OpusSwarm AI code review'
    required: false
    default: 'true'
  swarm-agents:
    description: 'Number of agents for swarm review (2-52)'
    required: false
    default: '8'
  review-depth:
    description: 'Swarm review depth: quick, standard, or thorough'
    required: false
    default: 'standard'
  aws-bedrock:
    description: 'Use AWS Bedrock for AI review (requires AWS credentials)'
    required: false
    default: 'false'
  aws-bedrock-model:
    description: 'Bedrock model: claude-3-sonnet, claude-3-haiku, titan-express'
    required: false
    default: 'claude-3-haiku'
  aws-security-hub:
    description: 'Export findings to AWS Security Hub'
    required: false
    default: 'false'
  aws-region:
    description: 'AWS region for Bedrock/Security Hub'
    required: false
    default: 'us-east-1'

outputs:
  integrity-score:
    description: 'Overall integrity score (0-100)'
  signature-status:
    description: 'Signature verification result'
  merkle-root:
    description: 'Computed Merkle root hash'
  policy-violations:
    description: 'Number of OPA policy violations'
  swarm-consensus:
    description: 'OpusSwarm consensus score (0.0-1.0)'
  agents-agreed:
    description: 'Number of agents that agreed on the review'
  report-url:
    description: 'URL to detailed integrity report'

runs:
  using: 'node20'
  main: 'dist/index.js'

# QUANTUM_WATERMARK: RAS=40668c787c463ca5 GODEL=v2.0 SWARM=52 TIME=2026-01-08
