name: 'Gödel Task Router'
description: 'Quantum-Classical Code Analysis with 52-Agent Swarm, EPOCH1 AST, Flash Sync @ 7777.77Hz'
author: 'EpochCore Quantum - AWS Partner (S-0084812)'
branding:
  icon: 'cpu'
  color: 'purple'

inputs:
  # Core Review
  mode:
    description: 'Review mode: quick, standard, deep'
    required: false
    default: 'standard'
  swarm-review:
    description: 'Enable 52-agent OpusSwarm AI review'
    required: false
    default: 'true'
  swarm-agents:
    description: 'Number of agents (2-52). Free: 8, Pro: 26, Enterprise: 52'
    required: false
    default: '8'

  # Auto-Fix Features (v3.0)
  auto-fix:
    description: '[FREE] Automatically fix security issues and code smells'
    required: false
    default: 'true'
  optimize:
    description: '[PRO] Apply code optimizations (var→const, remove console.log)'
    required: false
    default: 'false'
  compress:
    description: '[PRO] Generate minified versions of JS/CSS files'
    required: false
    default: 'false'
  watermark:
    description: '[PRO] Add quantum provenance watermarks to code files'
    required: false
    default: 'false'
  audit-deps:
    description: '[PRO] Audit and auto-fix vulnerable npm dependencies'
    required: false
    default: 'false'

  # Security Options
  signature-verify:
    description: 'Verify cryptographic signatures'
    required: false
    default: 'true'
  merkle-validate:
    description: 'Compute Merkle tree for file integrity'
    required: false
    default: 'true'
  fail-on-warning:
    description: 'Fail on warnings (not just errors)'
    required: false
    default: 'false'

  # Enterprise Options
  license-key:
    description: 'EpochCore license key for Pro ($29/mo) or Enterprise ($199/mo)'
    required: false
    default: ''
  worker-endpoint:
    description: 'Custom API endpoint (Enterprise)'
    required: false
    default: 'https://godel-task-router.com'

  # Quantum-Classical Mesh (v3.2)
  qcm-integration:
    description: '[PRO] Enable Quantum-Classical Mesh integration with 26-node swarm'
    required: false
    default: 'true'
  flash-sync:
    description: '[PRO] Enable Flash Sync Protocol @ 7777.77Hz resonance'
    required: false
    default: 'true'
  phi-amplification:
    description: '[PRO] Enable PHI (1.618) golden ratio amplification'
    required: false
    default: 'true'
  epoch1-ast:
    description: '[PRO] Enable EPOCH1 AST deep code analysis'
    required: false
    default: 'true'

  # AWS Integration (Enterprise)
  aws-bedrock:
    description: '[ENTERPRISE] Use AWS Bedrock Claude 3 for AI review'
    required: false
    default: 'false'
  aws-bedrock-model:
    description: 'Bedrock model: claude-3-sonnet, claude-3-haiku'
    required: false
    default: 'claude-3-haiku'
  aws-security-hub:
    description: '[ENTERPRISE] Export findings to AWS Security Hub'
    required: false
    default: 'false'
  aws-region:
    description: 'AWS region for Bedrock/Security Hub'
    required: false
    default: 'us-east-1'

outputs:
  integrity-score:
    description: 'Overall integrity score (0-100)'
  auto-fixes:
    description: 'Number of auto-fixes applied'
  security-fixes:
    description: 'Security issues automatically fixed'
  compression-saved:
    description: 'Bytes saved via compression'
  watermarks-added:
    description: 'Files watermarked with provenance'
  swarm-consensus:
    description: 'AI swarm consensus score (0.0-1.0)'
  merkle-root:
    description: 'Merkle root hash of all files'
  report-url:
    description: 'URL to detailed report'

  # QCM Outputs (v3.2)
  qcm-score:
    description: 'Quantum-Classical Mesh unified score (0-100)'
  quantum-coherence:
    description: 'Quantum state coherence (0.0-1.0)'
  swarm-nodes-active:
    description: 'Number of active swarm nodes (0-26)'
  flash-sync-status:
    description: 'Flash Sync status (SYNCED/PARTIAL/RESONANCE)'
  godel-signature:
    description: 'Gödel number signature for provenance'
  epoch1-ast-score:
    description: 'EPOCH1 AST analysis score (0-100)'

runs:
  using: 'node20'
  main: 'dist/index.js'

# QUANTUM_WATERMARK: GÖDEL_SEAL=40668c787c463ca5 V=3.2 QCM=true FLASH_SYNC=7777.77Hz EPOCH=2026-01-22
